---
php_upload_max_filesize: 1024M
php_post_max_size: 1024M
php_max_execution_time: 300
apache_listen_port: 8000
apache_create_vhosts: true
apache_vhosts_filename: "islandora.conf"
apache_remove_default_vhost: true
apache_vhosts:
  - servername: "claw.dev"
    documentroot: "/var/www/html/drupal/web"
    allow_override: All
    options: -Indexes +FollowSymLinks

php_memory_limit: -1
